---
- name: copy artifact.tar.gz to ec2 server
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: untar dist to /home/ubuntu
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: start pm2
  become: true
  shell: |
    cd /home/ubuntu
    pm2 start npm --name backend -- start