---
- name: Add the user 'node_exporter' without hom dir
  become: true
  user:
    name: node_exporter
    state: present
    shell: /bin/bash
    createhome: no

- name: Download node_exporter
  become: yes
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/ubuntu/
    mode: '0755'

- name: unarchive node_exporter
  become: yes
  unarchive: 
    src: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/ubuntu/
    mode: '0755'
    remote_src: yes

- name: Install node_exporter
  become: yes
  shell: |
    cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: Create node_exporter service
  become: yes
  template:
    src: "files/node-exporter.service"
    dest: "/etc/systemd/system/node-exporter.service"

- name: Configure systemd
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter

- name: Start prometheus
  become: yes
  shell: |
    systemctl start node-exporter

- name: Delete prometheus installer
  become: yes
  shell: |
    rm -rf /tmp/prometheus-2.19.0.linux-amd64.tar.gz